backend:
  name: git-gateway

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Sous-titre", name: "subtitle", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Corps", name: "body", widget: "markdown"}
#tags: ["bon-plans"]