backend:
  name: git-gateway

media_folder: "static/img"
public_folder: "img"

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Sous-titre", name: "subtitle", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Corps", name: "body", widget: "markdown"}
  - name: "page"
    label: "Page"
    folder: "content/page"
    create: false
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Sous-titre", name: "subtitle", widget: "string"}
      - {label: "Corps", name: "body", widget: "markdown"}
